# Create your models here.
from django.db import models

# Create your models here.
class registration_details(models.Model):
    fullname = models.CharField('fullname', max_length=30,null=True)
    username = models.CharField('username', max_length=30,primary_key =True,default="null")
    password = models.CharField('password', max_length=20, null=True)
    mobileno = models.CharField('mobileno', max_length=15,null=True)
    email = models.CharField('email', max_length=30,null=True)
    

class user_answers(models.Model):
    username = models.ForeignKey('registration_details',unique=True,primary_key=True,default="null", on_delete = models.CASCADE)
    q1 = models.FloatField('q1',null=True)
    q2 = models.FloatField('q2',null=True)
    q3 = models.FloatField('q3',null=True)
    q4 = models.FloatField('q4',null=True)
    q5 = models.FloatField('q5',null=True)
    q6 = models.FloatField('q6',null=True)
    q7 = models.FloatField('q7',null=True)
    q8 = models.FloatField('q8',null=True)
    q9 = models.FloatField('q9',null=True)
    q10 = models.FloatField('q10',null=True)
    q11 = models.FloatField('q11',null=True)
    q12 = models.FloatField('q12',null=True)
    q13 = models.FloatField('q13',null=True)
    q14 = models.FloatField('q14',null=True)
    q15 = models.FloatField('q15',null=True)
    q16 = models.FloatField('q16',null=True)
    q17 = models.FloatField('q17',null=True)
    q18 = models.FloatField('q18',null=True)
    q19 = models.FloatField('q19',null=True)
    q20 = models.FloatField('q20',null=True)
    q21 = models.FloatField('q21',null=True)
    q22 = models.FloatField('q22',null=True)
    q23 = models.FloatField('q23',null=True)
    q24 = models.FloatField('q24',null=True)
    q25 = models.FloatField('q25',null=True)
    q26 = models.FloatField('q26',null=True)
    q27 = models.FloatField('q27',null=True)
    q28 = models.FloatField('q28',null=True)
    q29 = models.FloatField('q29',null=True)
    q30 = models.FloatField('q30',null=True)
    q31 = models.FloatField('q31',null=True)
    q32 = models.FloatField('q32',null=True)
    q33 = models.FloatField('q33',null=True)
    q34 = models.FloatField('q34',null=True)
    q35 = models.FloatField('q35',null=True)
    q36 = models.FloatField('q36',null=True)
    q37 = models.FloatField('q37',null=True)
    q38 = models.FloatField('q38',null=True)
    q39 = models.FloatField('q39',null=True)
    q40 = models.FloatField('q40',null=True)
    q41 = models.FloatField('q41',null=True)
    q42 = models.FloatField('q42',null=True)
    q43 = models.FloatField('q43',null=True)
    q44 = models.FloatField('q44',null=True)
    q45 = models.FloatField('q45',null=True)
    q46 = models.FloatField('q46',null=True)
    q47 = models.FloatField('q47',null=True)
    q48 = models.FloatField('q48',null=True)
    q49 = models.FloatField('q49',null=True)
    q50 = models.FloatField('q50',null=True)

class clusterNum(models.Model):
    username = models.ForeignKey('registration_details',unique=True,primary_key=True,default="null", on_delete = models.CASCADE)
    clusNo = models.IntegerField('clusNo',null=True)
    extroversion = models.FloatField('extroversion',null=True)
    neurotic = models.FloatField('neurotic',null=True)
    agreeable = models.FloatField('agreeable',null=True)
    conscientious = models.FloatField('conscientious',null=True)
    openness = models.FloatField('openness',null=True)