# Generated by Django 4.0.1 on 2022-05-26 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration_details',
            fields=[
                ('fullname', models.CharField(max_length=30, null=True, verbose_name='fullname')),
                ('username', models.CharField(default='null', max_length=30, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='password')),
                ('mobileno', models.CharField(max_length=15, null=True, verbose_name='mobileno')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='clusterNum',
            fields=[
                ('username', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Personality.registration_details', unique=True)),
                ('clusNo', models.IntegerField(null=True, verbose_name='clusNo')),
                ('extroversion', models.FloatField(null=True, verbose_name='extroversion')),
                ('neurotic', models.FloatField(null=True, verbose_name='neurotic')),
                ('agreeable', models.FloatField(null=True, verbose_name='agreeable')),
                ('conscientious', models.FloatField(null=True, verbose_name='conscientious')),
                ('openness', models.FloatField(null=True, verbose_name='openness')),
            ],
        ),
        migrations.CreateModel(
            name='user_answers',
            fields=[
                ('username', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Personality.registration_details', unique=True)),
                ('q1', models.FloatField(null=True, verbose_name='q1')),
                ('q2', models.FloatField(null=True, verbose_name='q2')),
                ('q3', models.FloatField(null=True, verbose_name='q3')),
                ('q4', models.FloatField(null=True, verbose_name='q4')),
                ('q5', models.FloatField(null=True, verbose_name='q5')),
                ('q6', models.FloatField(null=True, verbose_name='q6')),
                ('q7', models.FloatField(null=True, verbose_name='q7')),
                ('q8', models.FloatField(null=True, verbose_name='q8')),
                ('q9', models.FloatField(null=True, verbose_name='q9')),
                ('q10', models.FloatField(null=True, verbose_name='q10')),
                ('q11', models.FloatField(null=True, verbose_name='q11')),
                ('q12', models.FloatField(null=True, verbose_name='q12')),
                ('q13', models.FloatField(null=True, verbose_name='q13')),
                ('q14', models.FloatField(null=True, verbose_name='q14')),
                ('q15', models.FloatField(null=True, verbose_name='q15')),
                ('q16', models.FloatField(null=True, verbose_name='q16')),
                ('q17', models.FloatField(null=True, verbose_name='q17')),
                ('q18', models.FloatField(null=True, verbose_name='q18')),
                ('q19', models.FloatField(null=True, verbose_name='q19')),
                ('q20', models.FloatField(null=True, verbose_name='q20')),
                ('q21', models.FloatField(null=True, verbose_name='q21')),
                ('q22', models.FloatField(null=True, verbose_name='q22')),
                ('q23', models.FloatField(null=True, verbose_name='q23')),
                ('q24', models.FloatField(null=True, verbose_name='q24')),
                ('q25', models.FloatField(null=True, verbose_name='q25')),
                ('q26', models.FloatField(null=True, verbose_name='q26')),
                ('q27', models.FloatField(null=True, verbose_name='q27')),
                ('q28', models.FloatField(null=True, verbose_name='q28')),
                ('q29', models.FloatField(null=True, verbose_name='q29')),
                ('q30', models.FloatField(null=True, verbose_name='q30')),
                ('q31', models.FloatField(null=True, verbose_name='q31')),
                ('q32', models.FloatField(null=True, verbose_name='q32')),
                ('q33', models.FloatField(null=True, verbose_name='q33')),
                ('q34', models.FloatField(null=True, verbose_name='q34')),
                ('q35', models.FloatField(null=True, verbose_name='q35')),
                ('q36', models.FloatField(null=True, verbose_name='q36')),
                ('q37', models.FloatField(null=True, verbose_name='q37')),
                ('q38', models.FloatField(null=True, verbose_name='q38')),
                ('q39', models.FloatField(null=True, verbose_name='q39')),
                ('q40', models.FloatField(null=True, verbose_name='q40')),
                ('q41', models.FloatField(null=True, verbose_name='q41')),
                ('q42', models.FloatField(null=True, verbose_name='q42')),
                ('q43', models.FloatField(null=True, verbose_name='q43')),
                ('q44', models.FloatField(null=True, verbose_name='q44')),
                ('q45', models.FloatField(null=True, verbose_name='q45')),
                ('q46', models.FloatField(null=True, verbose_name='q46')),
                ('q47', models.FloatField(null=True, verbose_name='q47')),
                ('q48', models.FloatField(null=True, verbose_name='q48')),
                ('q49', models.FloatField(null=True, verbose_name='q49')),
                ('q50', models.FloatField(null=True, verbose_name='q50')),
            ],
        ),
    ]
